### ISSUE TITLE
[2020.05.09] Back-end TODO list

### ISSUE THREAD

**Issue by MSWon** [kanban-project/Back-end#1]
## Back-end
- ```용근```
   - [ ] docker 환경 사용하여 Maria DB 구축 (호동님 스키마 토대로)
   - [ ] Django 기초 공부
   - [ ] Django <-> Maria DB (ORM)
   - [ ] Django API 만들기 연습
   - [ ] Frontend에서 요청받은 데이터를 API를 통해 어떻게 전달할지 고민

- ```현지```
   - [ ] docker 환경 사용하여 Maria DB 구축 (호동님 스키마 토대로)
   - [x] Django 기초 공부
   - [x] Django <-> Maria DB (ORM)
   - [ ] Django API 만들기 연습
   - [x] Frontend에서 요청받은 데이터를 API를 통해 어떻게 전달할지 고민
